### ISSUE TITLE
Error Writing Eeprom

### ISSUE THREAD

**Issue by manurafal** [bigtreetech/BIGTREETECH-SKR-E3-Turbo#30]
![photo_2021-02-07_16-13-34](https://user-images.githubusercontent.com/47554729/107150713-80e17180-695f-11eb-8bce-7b621ba88f4d.jpg)
![photo_2021-02-07_16-13-44](https://user-images.githubusercontent.com/47554729/107150721-850d8f00-695f-11eb-9042-7a2205468f03.jpg)

**Comment by manurafal** [comment]
[_Statusscreen.h.txt](https://github.com/bigtreetech/BIGTREETECH-SKR-E3-Turbo/files/5939235/_Statusscreen.h.txt)
[Configuration.h.txt](https://github.com/bigtreetech/BIGTREETECH-SKR-E3-Turbo/files/5939237/Configuration.h.txt)
[Configuration_adv.h.txt](https://github.com/bigtreetech/BIGTREETECH-SKR-E3-Turbo/files/5939238/Configuration_adv.h.txt)

**Comment by manurafal** [comment]
Ender 3 Pro    Skr E3 Turbo   TFT35_E3_V3
Marlin 2.0.7.2

**Comment by thrutheframe** [comment]
In VScode, remove or comment line no.51 from Marlin/src/HAL/LPC1768/HAL.h which defines a bogus I2C_ADDRESS macro 

//#define I2C_ADDRESS(A) uint8_t((A) << 1)

Save and compile. It should work.

**Comment by manurafal** [comment]
It is works. PERFECT!!!

Thanks a lot.

> 
> 
> In VScode, remove or comment line no.51 from Marlin/src/HAL/LPC1768/HAL.h which defines a bogus I2C_ADDRESS macro
> 
> //#define I2C_ADDRESS(A) uint8_t((A) << 1)
> 
> Save and compile. It should work.

It is works. PERFECT!!!

Thanks a lot.
