### ISSUE TITLE
sensorless homing not working

### ISSUE THREAD

**Issue by tome9111991** [bigtreetech/BIGTREETECH-SKR-E3-Turbo#44]
Hi there.

X and Y axis sensorless homing does not work.

The bed does not stop moving along the x and y axis when homing. I tried cranking the sensitivity all the way up to 255 but it still wouldn't stop at all. Any advice? 

Jumper for X and Y Diag are in

**Comment by ghost** [comment]
you have enabled steathchop and sensorless homing in the firmware?

**Comment by tome9111991** [comment]
Yes maybe i found the issue.
I comment 
```
#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
```
Im back to default 
it works now but not well.

With 90 STALL SENSITIVITY he moves a little bit hard to endstop.
With 91 STALL SENSITIVITY he moves 2-3mm and then is homed but not reach the endstop.

Im back to Sensor homing.
