### ISSUE TITLE
Can not flash anything to the card

### ISSUE THREAD

**Issue by DragonFlyer007** [bigtreetech/BIGTREETECH-SKR-E3-Turbo#58]
So brand new card, can not flash either marlin, klipper. I tried thru ssh with putty and kiuah, and also renaming .bin file and going thru micro SD. (with both psu power and only usb)

It does not flash and rename the .bin file on sd.

Thru ssh i will not flash either.

Also tried to flash new smoothie boothloader thru sd card, with nope. nothing there eiter.

Thru pronterface i run M115 and it says its Marlin 2.0 on it.
(Factory install!?) Or did one of my attempts go thru here ? Can NOT recall seeing a .bin file being renamed on my sd card.
Anyways,
I need klipper.

Going crazy, any other ways to force a flash thru?

Thanks

**Comment by radek8** [comment]
Use another SD card.
Preferably less than 8GB and formatted as FAT32 or FAT.

**Comment by DragonFlyer007** [comment]
> Use another SD card. Preferably less than 8GB and formatted as FAT32 or FAT.

I tried many cards, all in Fat32 and under 8 gb.

**Comment by DragonFlyer007** [comment]
After days of trail and error, i ended up starting from scratch, re-installed Octopi, and everything, then suddenly i was able to flash thru SD card with built .bin file thru KiauH.
Not really sure why i suddenly would flash, because i tried a million thingss at once at one point, but all good now.
