### ISSUE TITLE
DCDC Module question

### ISSUE THREAD

**Issue by Erehr** [bigtreetech/BIGTREETECH-SKR-E3-Turbo#66]
Can DCDC module for Mini E3 [(https://aliexpress.com/item/4000315602842.html](https://aliexpress.com/item/4000315602842.html) be used on E3 Turbo?
Layout and pins/distance between them seems to match
![unknown](https://user-images.githubusercontent.com/13292573/145584629-6db53936-08e7-45a7-b086-f5667d0ec86f.png)
.

**Comment by radek8** [comment]
Just look in the manual

![image](https://user-images.githubusercontent.com/46979052/145639730-468090a7-7126-426f-a79b-b6e0678fb775.png)

**Comment by dickysoe** [comment]
Hi, Sorry, I know this has been a while and closed. but do you really need the DCDC5V on E3 turbo? 
I read it already has 5V selection on the board itself.
