### ISSUE TITLE
Dual z axis

### ISSUE THREAD

**Issue by AMPens** [bigtreetech/BIGTREETECH-SKR-E3-Turbo#68]
Just install dual axis on my Ender 3. The problem I have is where do you connect the lead from the motor, 1 goes to the z pin out, where do you plug the other and do you need to add jumpers to this scocket

**Comment by Contrasens** [comment]
You now have 2 stepper motor cables, right? On the E3 Turbo board you have 2 options:
1. Connect the stepper cables to the ZMA and ZMB ports: the motors will work in sync, board is not aware that you have the second Z stepper
2. Connect one cable to the ZMA ( or ZMB) port, the second cable to the E1 port. You have to change in the firmware to tell it that.you connected the second Z cable into the E1 port. Advantage: you can use the automatic Z Align function ;)
