### ISSUE TITLE
i cannot get firmware to flash from sd card!

### ISSUE THREAD

**Issue by narcoad** [bigtreetech/BIGTREETECH-SKR-E3-Turbo#69]
I have tried to flash new firmware to motherboard and nothing happens the printer just starts as normal.  the Screen is the tft35-e3 v3.0  it says no printer attached i cannot move any axis or heat the hotend. thanks in advanced

**Comment by radek8** [comment]
Do you have a problem with uploading a new FW, or connecting a TFT display to a SKR board?

**Comment by narcoad** [comment]
its getting the firmware to flash from the sd card

**Comment by radek8** [comment]
SKR update:
Take an 8GB or smaller SD card.
Format to FAT32.
copy palt FW to SD card.
The name of the FW is firmware.bin
Insert the SD card into the SKR slot.
Restart the printer.
After successful upload, the file is renamed to firmware.cur
If that doesn't work, try another SD card. If that doesn't work either, use another SD ...

**Comment by radek8** [comment]
In order for the TFT display to connect, you must have the same serial configuration speed set on both the TFT and the SKR (115200).
You must also enable serial port 0 on the SKR for touch mode.
Enable "CR10_STOCKDISPLAY" for Marlin mode.
For Marlin mode, you must connect a 10-pin EXP3 cable.
Use a 5-pin TFT cable for touch mode.

I recommend updating the display to the latest FW.
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update
