### ISSUE TITLE
BLTouch not stopping z axis

### ISSUE THREAD

**Issue by Schm1m** [bigtreetech/BIGTREETECH-SKR-E3-Turbo#72]
Im trying to set up my (originally) Ender 3 Pro with the BTT SKR E3 Turbo with an Bltouch, but it wont stop the z axis stepper, if the probe is triggered

everything from [this](https://kay3d.com/pages/the-correct-way-to-configure-a-bltouch) guide works, until step 7) where it just doesn't stop

my configuration.h file:
[Configuration.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-E3-Turbo/files/7795002/Configuration.zip)

if any other file is required to help, just ask

**Comment by radek8** [comment]
Which connector do you have the probe connected to?

**Comment by Schm1m** [comment]
currently in the z-endstop connectors, so pin 1.27 i think

**Comment by radek8** [comment]
comment line
// # define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
Z-axis end stop connector connect to Z-PROBE connector (P1.22)
Pay attention to polarity

**Comment by Schm1m** [comment]
tried it with both polarities (as i wasnt sure), now the probe wont deploy on home-z, manual deploy over the lcd menu works

**Comment by radek8** [comment]
You must first determine the polarity in the manual and connect accordingly.
Experiment-mistake system, sooner or later you will destroy something.
 
With one 3D-Touch probe, I had a problem sensing position.
I had to adjust the screw in the sensor axis.

**Comment by Schm1m** [comment]
yeah, but even with the right polarity (according to the manual) the probe wont deploy on auto home

**Comment by radek8** [comment]
Send Configuration_adv.h

**Comment by Schm1m** [comment]
[Configuration_adv.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-E3-Turbo/files/7796753/Configuration_adv.zip)

**Comment by radek8** [comment]
uncomment
#define BLTOUCH_DELAY 500

**Comment by Schm1m** [comment]
probe still not deploying automatically

**Comment by radek8** [comment]
you send a video

**Comment by Schm1m** [comment]
[printer.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-E3-Turbo/files/7796793/printer.zip)

**Comment by Schm1m** [comment]
as shown, the probe does not deploy, but the printer sets the heigth as 0

**Comment by radek8** [comment]
Do you have the probe connected correctly?

**Comment by radek8** [comment]
send photo engagement

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/147837221-5ce7ef36-d428-4c65-882c-1764ffaae376.png)

**Comment by Schm1m** [comment]
![image](https://user-images.githubusercontent.com/96894708/147841645-bde0b421-e0a8-4183-9801-2487357ed055.png)
should be the same i guess

**Comment by radek8** [comment]
Check the yellow wire for poor crimp

**Comment by radek8** [comment]
send a photo of the connected connector on the BL-Touch probe

**Comment by Schm1m** [comment]
checked yellow wire with a multimeter, it has a negligible resistance near to 0, so it should work

![image](https://user-images.githubusercontent.com/96894708/147853058-3a0464dd-3239-46c4-b0d5-751ca71a9cb0.png)

**Comment by radek8** [comment]
The connector from BL Touch is crooked.
The pins on the connector are short and the yellow wire is lifted.
The yellow wire may not be in contact with the connector.

![image](https://user-images.githubusercontent.com/46979052/147853522-cb4707fc-3ddc-46b2-a7c8-1b4afb5340d6.png)

**Comment by radek8** [comment]
Is the connector fully depressed?

**Comment by radek8** [comment]
Is the connector fully depressed?

![image](https://user-images.githubusercontent.com/46979052/147853612-9e3e9cc5-0e3a-4cc5-9090-84b2d7e09cf8.png)
![image](https://user-images.githubusercontent.com/46979052/147853695-a3afbced-843a-4b9a-b2e8-47c43e2726f5.png)

**Comment by Schm1m** [comment]
everything should be plugged in properly

**Comment by radek8** [comment]
Another possible problem occurred to me.
BL Touch is a servo that is controlled by a PWM signal (yellow wire).
Your Marlin is out of date. Recently, Marlin had a problem generating a PWM signal. If you had these versions, it could be the cause of the problem.
Wouldn't you like to update Marlin to the latest versions to rule out this possibility?

Another option in what could be a problem is a faulty BlTouch. Could you try it in another printer that has BL Touch functional?

Another possible problem would be in the faulty pin P1.23. This could be tested by remapping to another pin, for example P1.24, which should also support PWM

**Comment by Schm1m** [comment]
i will try to adapt my config to the newest version. i can only try another BL Touch (Clone) on the same printer. for the last part it would be nice of you to give me a short description of how to do it.

**Comment by radek8** [comment]
OK,
If the Marlin update doesn't help and the BL Touch clone doesn't work on your printer, we remap the servo pin to another connector.

**Comment by Schm1m** [comment]
tried both "versions" of the BL-Touch, nothing has changed. I also tried both, the normal marlin (v 2.0.9.3) and bug-fix (2.0.x) also neither worked.

i don't know if this is the issue, but for me it seems, the printer "forgets" to deploy the probe when homing, so the probe in the "retracted" state returns the stopping signal, as it would hit the bed, before it can deploy.

**Comment by radek8** [comment]
If you let the probe eject from the LCD menu, will the probe eject?

**Comment by Schm1m** [comment]
yes it ejects and retracts fine manually

**Comment by radek8** [comment]
You can try to allow

#define NUM_SERVOS 1
in configuration.h

**Comment by Schm1m** [comment]
uncommented "NUM_SERVOS" and set it to 1, nothing changed

**Comment by radek8** [comment]
Then I can't think of anything ...

**Comment by Schm1m** [comment]
well... i got it working now

you probably fixed my initial problem with any of the changes you told me to do, but opened another one. 
by not using the option Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN, "USE_PROBE_FOR_Z_HOMING" wasn't automatically called, as the comment a few lines above states. because of this i uncommented "USE_PROBE_FOR_Z_HOMING" and now it deploys AND stops after hitting someting.

so, thanks for the help and quick answers

**Comment by radek8** [comment]
But, in the configuration you submitted, "#define USE_PROBE_FOR_Z_HOMING" has been enabled.

**Comment by radek8** [comment]
Mainly that it works.
Happy press.

**Comment by Schm1m** [comment]
yeah, i dont know why it changed, but now im glad it works, so now onto the finetuning
