### ISSUE TITLE
E3 Turbo DIY pins

### ISSUE THREAD

**Issue by mlaci001** [bigtreetech/BIGTREETECH-SKR-E3-Turbo#75]
Hi,
The description includes:

"Add one I2C bus expansion interface and one UART expansion interface for customer DIY use".

What are these PINs? Where can I find these.
I need these PINs to connect an ESP8266.
Thanks.

**Comment by radek8** [comment]
You can find them in the AUX-2 connector

**Comment by radek8** [comment]
SDA2 -> TX2 - P0.10
SCL2  -> RX2 - P0.11 

SDA0 - P0.27
SCL0  - P0.28

![image](https://user-images.githubusercontent.com/46979052/151238026-145f5a0c-63d6-45b0-9de8-dbeef9c3b5b9.png)

**Comment by mlaci001** [comment]
Thanks a lot !
Is this motherboard suitable for Ender-3 PRO?
The hot bed (24V / 220W / 2.6 ohm / 9.2A). 
The AUX-2 connector SDA0 SCL0 pins  what outlets ?

**Comment by radek8** [comment]
The board is named E3 as Ender3.
The screw holes are spaced the same as Ender3

The title page reads:

BIGTREETECH SKR Mini E3 V2.x přidal další hardwarová vylepšení a vylepšení na základě zpětné vazby od komunity. Tato vylepšení a vylepšení s SKR Mini E3 V2.x zahrnují mimo jiné dva porty rozhraní pro osu Z a SKR Mini E3 V2.x plus BIGTREETECH SKR E3 Turbo je dnes kromě 3D tiskáren, které již SKR podporuje. Desky Mini E3 V1.x, také kompatibilní s 3D tiskárnami CR-10S, CR-10 S4, CR-10 S5, Ender 5, Ender 5 Pro a Ender 5 Plus od Creality.

**Comment by mlaci001** [comment]
Hi,
Can I use "#define SERIAL_PORT_2 3" in Marlin?

**Comment by radek8** [comment]
No.
You use
#define SERIAL_PORT_2 2

In the processor specification, pins P0.10 and P0.11 are listed as Uart2
I wrote it at the beginning of the ticket

![image](https://user-images.githubusercontent.com/46979052/151397716-60400446-bffb-4858-800d-167317bbd052.png)

![image](https://user-images.githubusercontent.com/46979052/151399021-caaabf87-ecf7-4baa-b657-cc7ba14503f1.png)


![image](https://user-images.githubusercontent.com/46979052/151398319-c7f10275-a834-4928-a473-f961775a39f4.png)

**Comment by radek8** [comment]
You can also use UATR0
But then you will have nowhere to connect the touch screen

![image](https://user-images.githubusercontent.com/46979052/151450694-4a9c3aba-0c46-4e49-8a30-a4f298b136a6.png)

**Comment by radek8** [comment]
> Hi, Can I use "#define SERIAL_PORT_2 3" in Marlin?

The index for the letters RT and TX indicates the serial port number that you must define in Marlin.
RX2, TX2 set port 2 in Marlin
RX0, TX0 set port 0 in marlin

PS: I am not a representative of the manufacturer :-)
