### ISSUE TITLE
Can i change microstepping value ?

### ISSUE THREAD

**Issue by mlaci001** [bigtreetech/BIGTREETECH-SKR-E3-Turbo#77]
Are there digital microstepping pins on this card?
Marlin says "Unknown command: M503"
When I switch to 256 (e.g. #define X_MICROSTEPS 256), it works, but very slowly (I think at 1/16 speed). It's like it works, but Marlin wouldn't notice the change.

**Comment by radek8** [comment]
You must enable the M503 in a Marlin configuration
comment
// # define DISABLE_M503
