### ISSUE TITLE
Ender 3V2 with BIGTREETECH SKR Mini E3 v3

### ISSUE THREAD

**Issue by Dplayer82** [bigtreetech/BIGTREETECH-SKR-E3-Turbo#79]
Please help me. I changed my board.
I connected the ribbon cable of the display by replacing it according to the instructions... but the screen balck.
I need firmware, but i couldn't find a working one.
Unfortunately, I don't know how to rewrite Marlin.
Can anyone send it?

**Comment by radek8** [comment]
You are writing in the wrong place.
SKR E3 Turbo does not equal SKR mini E3 V3
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/issues

Close the ticket
